[package]
name = "nifsys"
version = "0.0.2"
authors = ["Daniel Goertzen <daniel.goertzen@gmail.com>"]

[lib]
name = "nifsys"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.0-rc.1"
lazy_static = "1.2.0"
